import weaviate
import os
from weaviate.classes.config import Configure, VectorDistances, DataType, Property

WEAVIATE_HOST = os.getenv("WEAVIATE_HOST", default="localhost")
collection_name = "documents"
client = weaviate.connect_to_local(host=WEAVIATE_HOST, port=8090)
properties = [
    Property(
        name="file_path",
        data_type=DataType.TEXT,
        description=None,
        indexFilterable=None,
        indexSearchable=None,
        indexRangeFilters=None,
        nestedProperties=None,
        skip_vectorization=True,
        tokenization=None,
        vectorize_property_name=False,
    ),
    Property(
        name="file_name",
        data_type=DataType.TEXT,
        description=None,
        indexFilterable=None,
        indexSearchable=None,
        indexRangeFilters=None,
        nestedProperties=None,
        skip_vectorization=True,
        tokenization=None,
        vectorize_property_name=False,
    ),
    Property(
        name="file_type",
        data_type=DataType.TEXT,
        description=None,
        indexFilterable=None,
        indexSearchable=None,
        indexRangeFilters=None,
        nestedProperties=None,
        skip_vectorization=True,
        tokenization=None,
        vectorize_property_name=False,
    ),
    Property(
        name="file_size",
        data_type=DataType.INT,
        description=None,
        indexFilterable=None,
        indexSearchable=None,
        indexRangeFilters=None,
        nestedProperties=None,
        skip_vectorization=True,
        tokenization=None,
        vectorize_property_name=False,
    ),
    Property(
        name="creation_date",
        data_type=DataType.DATE,
        description=None,
        indexFilterable=None,
        indexSearchable=None,
        indexRangeFilters=None,
        nestedProperties=None,
        skip_vectorization=True,
        tokenization=None,
        vectorize_property_name=False,
    ),
    Property(
        name="last_modified_date",
        data_type=DataType.DATE,
        description=None,
        indexFilterable=None,
        indexSearchable=None,
        indexRangeFilters=None,
        nestedProperties=None,
        skip_vectorization=True,
        tokenization=None,
        vectorize_property_name=False,
    ),
    Property(
        name="text",
        data_type=DataType.TEXT,
        description=None,
        indexFilterable=None,
        indexSearchable=None,
        indexRangeFilters=None,
        nestedProperties=None,
        skip_vectorization=False,
        tokenization=None,
        vectorize_property_name=False,
    ),
    Property(
        name="link",
        data_type=DataType.TEXT,
        description=None,
        indexFilterable=None,
        indexSearchable=None,
        indexRangeFilters=None,
        nestedProperties=None,
        skip_vectorization=True,
        tokenization=None,
        vectorize_property_name=False,
    ),
]
if not client.collections.exists(collection_name):
    client.collections.create(
        name="documents",
        properties=properties,
        vectorizer_config=Configure.Vectorizer.none(),
        vector_index_config=Configure.VectorIndex.hnsw(
            distance_metric=VectorDistances.COSINE
        ),
    )
client.close()
